export const notes = [
    { id: 'AWS_CCP', title: 'AWS CCP Study Notes', file: 'AWS_CCP.md' },
    { id: 'Accessibility', title: 'Accessibility', file: 'Accessibility.md' },
    { id: 'APIs', title: 'APIs', file: 'APIs.md' },
    { id: 'CSS', title: 'CSS', file: 'CSS.md' },
    { id: 'CI/CD', title: 'CI/CD', file: 'CI/CD.md' },
    { id: 'DesignPatterns', title: 'Design Patterns', file: 'DesignPatterns.md' },
    { id: 'Docker', title: 'Docker', file: 'Docker.md' },
    { id: 'GraphQL', title: 'GraphQL', file: 'GraphQL.md' },
    { id: 'Javascript', title: 'JavaScript', file: 'Javascript.md' },
    { id: 'Kafka', title: 'Kafka', file: 'Kafka.md' },
    { id: 'NestJS', title: 'NestJS', file: 'NestJS.md' },
    { id: 'Python', title: 'Python', file: 'Python.md' },
    { id: 'React', title: 'React', file: 'React.md' },
    { id: 'RelationalDatabases', title: 'Relational Databases', file: 'RelationalDatabases.md' },
    { id: 'Security', title: 'Security', file: 'Security.md' },
    { id: 'Testing', title: 'Testing', file: 'Testing.md' },
    { id: 'Typescript', title: 'TypeScript', file: 'Typescript.md' },
  ];
  